version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY:-pk_test_placeholder}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY:-sk_test_placeholder}
      - NEXT_PUBLIC_CLERK_SIGN_IN_URL=/sign-in
      - NEXT_PUBLIC_CLERK_SIGN_UP_URL=/sign-up
      - NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL=/
      - NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL=/
      - POWERBI_CLIENT_ID=${POWERBI_CLIENT_ID:-placeholder}
      - POWERBI_CLIENT_SECRET=${POWERBI_CLIENT_SECRET:-placeholder}
      - POWERBI_TENANT_ID=${POWERBI_TENANT_ID:-placeholder}
      - POWERBI_SCOPE=${POWERBI_SCOPE:-https://analysis.windows.net/powerbi/api/.default}
      - POWERBI_REPORT_ID=${POWERBI_REPORT_ID:-placeholder}
      - POWERBI_WORKSPACE_ID=${POWERBI_WORKSPACE_ID:-placeholder}
      - POWERBI_DATASET_ID=${POWERBI_DATASET_ID:-placeholder}
      - POWERBI_EMBED_URL=${POWERBI_EMBED_URL:-https://app.powerbi.com/reportEmbed}
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-your_openai_api_key_here}
    restart: unless-stopped

networks:
  default:
    name: powerbi-chat-dev-network